// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct CounterDappClientProgram;

impl CounterDappClientProgram {
    pub const ROUTE_ID_COUNTER: u8 = 1;
}

impl sails_rs::client::Program for CounterDappClientProgram {}

pub trait CounterDappClient {
    type Env: sails_rs::client::GearEnv;
    fn counter(&self) -> sails_rs::client::Service<counter::CounterImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> CounterDappClient
    for sails_rs::client::Actor<CounterDappClientProgram, E>
{
    type Env = E;
    fn counter(&self) -> sails_rs::client::Service<counter::CounterImpl, Self::Env> {
        self.service(CounterDappClientProgram::ROUTE_ID_COUNTER)
    }
}
pub trait CounterDappClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<CounterDappClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> CounterDappClientCtors
    for sails_rs::client::Deployment<CounterDappClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<CounterDappClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> (), 0);
}

pub mod counter {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum CounterError {
        Unauthorized,
    }

    pub trait Counter {
        type Env: sails_rs::client::GearEnv;
        fn decrement(&mut self) -> sails_rs::client::PendingCall<io::Decrement, Self::Env>;
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env>;
        fn reset(&mut self) -> sails_rs::client::PendingCall<io::Reset, Self::Env>;
        fn value(&self) -> sails_rs::client::PendingCall<io::Value, Self::Env>;
    }

    pub struct CounterImpl;

    impl sails_rs::client::Identifiable for CounterImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([242, 138, 222, 234, 92, 8, 246, 58]);
    }

    impl<E: sails_rs::client::GearEnv> Counter for sails_rs::client::Service<CounterImpl, E> {
        type Env = E;
        fn decrement(&mut self) -> sails_rs::client::PendingCall<io::Decrement, Self::Env> {
            self.pending_call(())
        }
        fn increment(&mut self) -> sails_rs::client::PendingCall<io::Increment, Self::Env> {
            self.pending_call(())
        }
        fn reset(&mut self) -> sails_rs::client::PendingCall<io::Reset, Self::Env> {
            self.pending_call(())
        }
        fn value(&self) -> sails_rs::client::PendingCall<io::Value, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Decrement () -> i32, 0, <super::CounterImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Increment () -> i32, 1, <super::CounterImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Reset () -> super::Result<(), super::CounterError, >, 2, <super::CounterImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Value () -> i32, 3, <super::CounterImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }
}
